id = "asciidoc"
name = "AsciiDoc"
version = "0.1.0"
schema_version = 1
authors = ["bovinemagnet"]
description = "AsciiDoc, Asciidoctor, and Antora language support"
repository = "https://github.com/bovinemagnet/zed-asciidoc"
snippets = ["./snippets/asciidoc.json"]

[language_servers.adoc-ls]
name = "adoc-ls"
languages = ["AsciiDoc"]

[grammars.asciidoc]
repository = "https://github.com/bovinemagnet/tree-sitter-asciidoc"
rev = "a4fc9d7217502664b7a08fb028377a3c5dc4350e"
path = "tree-sitter-asciidoc"

[grammars.asciidoc_inline]
repository = "https://github.com/bovinemagnet/tree-sitter-asciidoc"
rev = "a4fc9d7217502664b7a08fb028377a3c5dc4350e"
path = "tree-sitter-asciidoc_inline"
