[package]
name = "adoc-ls"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
adoc-antora = { path = "../adoc-antora" }
adoc-core = { path = "../adoc-core" }
adoc-index = { path = "../adoc-index" }
adoc-parser = { path = "../adoc-parser" }
adoc-render = { path = "../adoc-render" }
lsp-server = "=0.10.0"
lsp-types = "=0.97.0"
serde = "=1.0.229"
serde_json = "=1.0.151"
url = "=2.5.8"

[lints]
workspace = true
